modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/OrderedChaos-Dev/Mobtastic/issues"
license="lol"

[[mods]]
	modId="mobtastic"
	version="${version}"
	displayName="Mobtastic"
	displayURL="https://www.orderedchaos.dev/"
	logoFile="mobtastic.png"
	authors="solis_nova"
	description='''
	Adds vanilla style mobs!
	'''
[[dependencies.mobtastic]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mobtastic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,]"
    ordering="NONE"
    side="BOTH"
